[project]
name = "chimcla"
version = "0.2.0"


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# [project.package]
[tool.setuptools.packages.find]
where = ["src"]



[project.scripts]
chocolate_bgr_convert = "chimcla.cli:bgr_convert"
chocolate_create_groups = "chimcla.cli:create_groups"
chocolate_rename_cell_imgs = "chimcla.cli:rename_cell_imgs"
